# Site settings
title: EnPub-英璞
email: enpub@outlook.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.enpub.cn" # the base hostname & protocol for your site

#twitter_username:
#github_username:

# Build settings
markdown: kramdown
