# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EnPub -- 英璞文化
email: enpub@outlook.com
description: Professional English Editing Service for Your Career Success
baseurl: "" # the subpath of your site, e.g. /blog

theme: jekyll-theme-leap-day
#url: "http://www.enpub.cn" # the base hostname & protocol for your site
url: "127.0.0.1:4000"

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
